### ISSUE TITLE
Incompatible with CMK 2.1.0

### ISSUE THREAD

**Issue by BigBadBassMan** [Haeki/esendex_notification_plugin#1]
* Wato plugin cannot be loaded due to Integer fields having no "allow_empty" property anymore
* notification plugin is python2 and not python3
** message.decode("ascii") is not defined for strings in python 3
** module requests seems not to be preinstalled in CMK

**Comment by Haeki** [comment]
Fixed in [Version 2.4.1](https://github.com/Haeki/esendex_notification_plugin/releases/tag/2.4.1)
